//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Person = new HashSet<Person>();
            this.Person1 = new HashSet<Person>();
        }
    
        public int cityId { get; set; }
        public string postalOffice { get; set; }
        public string postalCode { get; set; }
        public string cityPart { get; set; }
        public string county { get; set; }
    
        public virtual ICollection<Person> Person { get; set; }
        public virtual ICollection<Person> Person1 { get; set; }
    }
}
