//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosis
    {
        public Diagnosis()
        {
            this.Presciption = new HashSet<Presciption>();
        }
    
        public int diagnosisId { get; set; }
        public int appointmentId { get; set; }
        public int diseaseId { get; set; }
        public string note { get; set; }
        public string treatment { get; set; }
    
        public virtual Disease Disease { get; set; }
        public virtual DoctorsAppointment DoctorsAppointment { get; set; }
        public virtual ICollection<Presciption> Presciption { get; set; }
    }
}
