//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disease
    {
        public Disease()
        {
            this.Diagnosis = new HashSet<Diagnosis>();
            this.PatientChronicalDisease = new HashSet<PatientChronicalDisease>();
        }
    
        public int ICDId { get; set; }
        public string ICDCode { get; set; }
        public string ICDTytle { get; set; }
    
        public virtual ICollection<Diagnosis> Diagnosis { get; set; }
        public virtual ICollection<PatientChronicalDisease> PatientChronicalDisease { get; set; }
    }
}
