//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorsAppointment
    {
        public DoctorsAppointment()
        {
            this.Diagnosis = new HashSet<Diagnosis>();
        }
    
        public int doctorsAppointmetnId { get; set; }
        public System.DateTime appointmentDate { get; set; }
        public string symptopms { get; set; }
        public string note { get; set; }
        public int specificMedicalRecordId { get; set; }
    
        public virtual ICollection<Diagnosis> Diagnosis { get; set; }
        public virtual MedicalRecord MedicalRecord { get; set; }
    }
}
