//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorSpecialisation
    {
        public DoctorSpecialisation()
        {
            this.DoctorsCompetence = new HashSet<DoctorsCompetence>();
            this.MedicalRecord = new HashSet<MedicalRecord>();
        }
    
        public int doctorSpecialisationId { get; set; }
        public string doctorSpecialisation1 { get; set; }
    
        public virtual ICollection<DoctorsCompetence> DoctorsCompetence { get; set; }
        public virtual ICollection<MedicalRecord> MedicalRecord { get; set; }
    }
}
