//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHealth.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EHealthDB2Entities : DbContext
    {
        public EHealthDB2Entities()
            : base("name=EHealthDB2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<City> City { get; set; }
        public DbSet<Diagnosis> Diagnosis { get; set; }
        public DbSet<Disease> Disease { get; set; }
        public DbSet<DoctorsAppointment> DoctorsAppointment { get; set; }
        public DbSet<DoctorsCompetence> DoctorsCompetence { get; set; }
        public DbSet<DoctorSpecialisation> DoctorSpecialisation { get; set; }
        public DbSet<Email> Email { get; set; }
        public DbSet<HealthInsurance> HealthInsurance { get; set; }
        public DbSet<Image> Image { get; set; }
        public DbSet<MedicalRecord> MedicalRecord { get; set; }
        public DbSet<Medicine> Medicine { get; set; }
        public DbSet<PatientChronicalDisease> PatientChronicalDisease { get; set; }
        public DbSet<Person> Person { get; set; }
        public DbSet<PhoneNumber> PhoneNumber { get; set; }
        public DbSet<PhoneType> PhoneType { get; set; }
        public DbSet<Presciption> Presciption { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
