//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public Image()
        {
            this.Person = new HashSet<Person>();
        }
    
        public int imageId { get; set; }
        public byte[] image1 { get; set; }
    
        public virtual ICollection<Person> Person { get; set; }
    }
}
