//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public Medicine()
        {
            this.Presciption = new HashSet<Presciption>();
        }
    
        public int medicneId { get; set; }
        public string ATKId { get; set; }
        public string medicineName { get; set; }
        public string medicineFactory { get; set; }
        public string medicineLongName { get; set; }
        public string usage { get; set; }
        public string package { get; set; }
    
        public virtual ICollection<Presciption> Presciption { get; set; }
    }
}
