//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalRecord
    {
        public MedicalRecord()
        {
            this.DoctorsAppointment = new HashSet<DoctorsAppointment>();
        }
    
        public int medicalRecordId { get; set; }
        public int doctorId { get; set; }
        public int personId { get; set; }
        public int doctorSpecialisationId { get; set; }
    
        public virtual ICollection<DoctorsAppointment> DoctorsAppointment { get; set; }
        public virtual DoctorSpecialisation DoctorSpecialisation { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
