//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientChronicalDisease
    {
        public int personId { get; set; }
        public int diseaseId { get; set; }
        public System.DateTime dateOfDiagnose { get; set; }
    
        public virtual Disease Disease { get; set; }
        public virtual Person Person { get; set; }
    }
}
