//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneType
    {
        public PhoneType()
        {
            this.PhoneNumber = new HashSet<PhoneNumber>();
        }
    
        public int phoneTypeId { get; set; }
        public string phoneType1 { get; set; }
    
        public virtual ICollection<PhoneNumber> PhoneNumber { get; set; }
    }
}
