//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presciption
    {
        public int diagnosisId { get; set; }
        public int medicineId { get; set; }
        public string note { get; set; }
    
        public virtual Diagnosis Diagnosis { get; set; }
        public virtual Medicine Medicine { get; set; }
    }
}
